var searchData=
[
  ['image_0',['Image',['../d6/d2d/structpl_volume_collection_1_1_image.htm',1,'plVolumeCollection']]],
  ['imageviewcachekey_1',['ImageViewCacheKey',['../d6/daa/structpl_image_copy_vulkan_1_1_image_view_cache_key.htm',1,'plImageCopyVulkan']]],
  ['imageviewcachevalue_2',['ImageViewCacheValue',['../dc/dde/structpl_image_copy_vulkan_1_1_image_view_cache_value.htm',1,'plImageCopyVulkan']]],
  ['impl_3',['Impl',['../d0/d30/classpl_internal_1_1_message_handler_1_1_impl.htm',1,'plInternal::MessageHandler&lt; bIsConst &gt;::Impl&lt; Class, MessageType, Method &gt;'],['../d3/dca/classpl_internal_1_1_message_handler_3_01true_01_4_1_1_impl.htm',1,'plInternal::MessageHandler&lt; true &gt;::Impl']]],
  ['importer_4',['Importer',['../db/df8/classpl_model_importer2_1_1_importer.htm',1,'plModelImporter2']]],
  ['importerassimp_5',['ImporterAssimp',['../d5/d4e/classpl_model_importer2_1_1_importer_assimp.htm',1,'plModelImporter2']]],
  ['importermagicavoxel_6',['ImporterMagicaVoxel',['../db/d6d/classpl_model_importer2_1_1_importer_magica_voxel.htm',1,'plModelImporter2']]],
  ['importersourcebsp_7',['ImporterSourceBSP',['../d6/dbb/classpl_model_importer2_1_1_importer_source_b_s_p.htm',1,'plModelImporter2']]],
  ['importmode_8',['ImportMode',['../d3/d75/structpl_asset_document_generator_1_1_import_mode.htm',1,'plAssetDocumentGenerator']]],
  ['importoptions_9',['ImportOptions',['../d7/dc5/structpl_model_importer2_1_1_import_options.htm',1,'plModelImporter2']]],
  ['init_10',['Init',['../dd/d5f/structpl_plugin_1_1_init.htm',1,'plPlugin']]],
  ['input_11',['Input',['../d3/d4b/structpl_expression_a_s_t_1_1_input.htm',1,'plExpressionAST::Input'],['../d8/d83/structpl_math_expression_1_1_input.htm',1,'plMathExpression::Input'],['../dd/d1a/structpl_virtual_thumb_stick_1_1_input.htm',1,'plVirtualThumbStick::Input']]],
  ['inputeventdata_12',['InputEventData',['../d3/dcc/structpl_input_manager_1_1_input_event_data.htm',1,'plInputManager']]],
  ['instancedata_13',['InstanceData',['../d1/d3d/structpl_state_machine_internal_1_1_compound_1_1_instance_data.htm',1,'plStateMachineInternal::Compound']]],
  ['instanceptr_14',['InstancePtr',['../d2/dd9/unionpl_delegate_base_1_1_instance_ptr.htm',1,'plDelegateBase']]],
  ['instantiationcontextbase_15',['InstantiationContextBase',['../d6/d4e/classpl_world_reader_1_1_instantiation_context_base.htm',1,'plWorldReader']]],
  ['intensitycp_16',['IntensityCP',['../d4/d59/structpl_color_gradient_1_1_intensity_c_p.htm',1,'plColorGradient']]],
  ['interactioncontact_17',['InteractionContact',['../d4/def/structpl_jolt_contact_events_1_1_interaction_contact.htm',1,'plJoltContactEvents']]],
  ['interactioncontext_18',['InteractionContext',['../d1/d0e/structpl_qt_engine_view_widget_1_1_interaction_context.htm',1,'plQtEngineViewWidget']]],
  ['interfaceimpl_19',['InterfaceImpl',['../d2/d66/structpl_world_module_config_1_1_interface_impl.htm',1,'plWorldModuleConfig']]],
  ['invalidatedarea_20',['InvalidatedArea',['../db/d33/structpl_proc_gen_internal_1_1_invalidated_area.htm',1,'plProcGenInternal']]],
  ['item_21',['Item',['../df/dfa/structpl_dynamic_menu_action_1_1_item.htm',1,'plDynamicMenuAction::Item'],['../d6/d38/structpl_texture_atlas_creation_desc_1_1_item.htm',1,'plTextureAtlasCreationDesc::Item'],['../d8/de7/structpl_texture_atlas_runtime_desc_1_1_item.htm',1,'plTextureAtlasRuntimeDesc::Item']]],
  ['itemflags_22',['ItemFlags',['../d0/d1b/structpl_dynamic_menu_action_1_1_item_1_1_item_flags.htm',1,'plDynamicMenuAction::Item']]],
  ['iterator_23',['Iterator',['../d8/d76/classpl_block_storage_1_1_iterator.htm',1,'plBlockStorage&lt; T, BlockSizeInByte, StorageType &gt;::Iterator'],['../d7/d04/structpl_id_table_base_1_1_iterator.htm',1,'plIdTableBase&lt; IdType, ValueType &gt;::Iterator'],['../d9/dde/structpl_list_base_1_1_iterator.htm',1,'plListBase&lt; T &gt;::Iterator'],['../d5/d4f/classpl_memory_tracker_1_1_iterator.htm',1,'plMemoryTracker::Iterator'],['../dd/dc0/structpl_range_view_1_1_iterator.htm',1,'plRangeView&lt; ValueType, IteratorType &gt;::Iterator'],['../d7/dde/classpl_render_data_batch_1_1_iterator.htm',1,'plRenderDataBatch::Iterator&lt; T &gt;'],['../d5/dd5/classpl_tag_set_template_1_1_iterator.htm',1,'plTagSetTemplate&lt; BlockStorageAllocator &gt;::Iterator']]],
  ['iterator_5fbase_24',['iterator_base',['../db/d66/structiterator__base.htm',1,'']]],
  ['iteratorbase_25',['IteratorBase',['../d4/de2/structpl_set_base_1_1_iterator_base.htm',1,'plSetBase']]]
];
